title: Marc Ed. Raffalli
baseurl: ''

google_analytics: UA-97591265-1

author_name: Marc Ed. Raffalli
email: raffalli.marc.ed@hotmail.fr
github_username:  marc-ed-raffalli

copyright: Â© 2019 - Marc Ed. Raffalli

networks:
  - name: linkedin
    url:  https://www.linkedin.com/in/marc-ed-raffalli/
    icon: ion-logo-linkedin
  - name: github
    url:  https://github.com/marc-ed-raffalli/
    icon: ion-logo-github

menu:
  - ref:  projects
  - ref:  posts

exclude:
  - .idea
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts
  - package.json

sass:
  style: compressed
